-- ════════════════════════════════════════════════════════════
-- secondpro 프로젝트 테이블 생성 SQL
-- 기준: Oracle / DBeaver / MyBatis · DB 계정: secondpro
-- 실행 순서: member → social_account → chat_room → chat_message
--            → board → board_file → board_comment
-- ════════════════════════════════════════════════════════════


-- ════════════════════════════════════════════════════════════
-- [1] 회원(MEMBER) 테이블
-- ════════════════════════════════════════════════════════════
CREATE TABLE member (
    no               NUMBER GENERATED BY DEFAULT AS IDENTITY,
    member_id        VARCHAR2(100 CHAR),
    password         VARCHAR2(255 CHAR),
    name             VARCHAR2(50 CHAR),
    nickname         VARCHAR2(50 CHAR) NOT NULL,
    email            VARCHAR2(100 CHAR),
    phone            VARCHAR2(20 CHAR),
    birth_date       DATE,
    gender           VARCHAR2(10 CHAR),
    postcode         VARCHAR2(10 CHAR),
    address          VARCHAR2(255 CHAR),
    detail_address   VARCHAR2(255 CHAR),
    role             VARCHAR2(20 CHAR) DEFAULT 'USER' NOT NULL,
    profile_image    VARCHAR2(500 CHAR),
    last_login_date  TIMESTAMP,
    agree_terms_yn   CHAR(1)   DEFAULT 'N'          NOT NULL,
    agree_privacy_yn CHAR(1)   DEFAULT 'N'          NOT NULL,
    regdate          TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,

    CONSTRAINT pk_member PRIMARY KEY (no),
    CONSTRAINT uk_member_member_id UNIQUE (member_id),
    CONSTRAINT uk_member_email UNIQUE (email),
    CONSTRAINT ck_member_role CHECK (role IN ('USER', 'ADMIN')),
    CONSTRAINT ck_member_agree_terms CHECK (agree_terms_yn IN ('Y', 'N')),
    CONSTRAINT ck_member_agree_privacy CHECK (agree_privacy_yn IN ('Y', 'N'))
);


-- ════════════════════════════════════════════════════════════
-- [2] 소셜 계정(SOCIAL_ACCOUNT) 테이블
-- ════════════════════════════════════════════════════════════
CREATE TABLE social_account (
    no           NUMBER GENERATED BY DEFAULT AS IDENTITY,
    member_no    NUMBER                         NOT NULL,
    provider     VARCHAR2(30 CHAR) NOT NULL,
    provider_id  VARCHAR2(255 CHAR) NOT NULL,
    created_date TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,

    CONSTRAINT pk_social_account PRIMARY KEY (no),
    CONSTRAINT uk_social_provider UNIQUE (provider, provider_id),
    CONSTRAINT fk_social_member FOREIGN KEY (member_no)
        REFERENCES member (no) ON DELETE CASCADE
);


-- ════════════════════════════════════════════════════════════
-- [3] 1:1 문의 - 채팅방(CHAT_ROOM) 테이블
-- ════════════════════════════════════════════════════════════
CREATE TABLE chat_room (
   room_no           NUMBER GENERATED BY DEFAULT AS IDENTITY,
   user_no           NUMBER,
   admin_no          NUMBER,
   status            VARCHAR2(20 CHAR) DEFAULT 'OPEN' NOT NULL,
   category          VARCHAR2(30 CHAR) DEFAULT 'ETC' NOT NULL,
   last_message      VARCHAR2(1000 CHAR),
   last_message_date TIMESTAMP,
   created_date      TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
   closed_date       TIMESTAMP,

   CONSTRAINT pk_chat_room PRIMARY KEY (room_no),
   CONSTRAINT ck_chat_room_status CHECK (status IN ('OPEN', 'CLOSED')),
   CONSTRAINT ck_chat_room_category CHECK (
       category IN ('MAIL', 'MAP', 'STOCK', 'NEWS', 'WEATHER', 'CALENDAR', 'ETC')
       ),
   CONSTRAINT fk_chat_room_user FOREIGN KEY (user_no)
       REFERENCES member (no) ON DELETE SET NULL,
   CONSTRAINT fk_chat_room_admin FOREIGN KEY (admin_no)
       REFERENCES member (no) ON DELETE SET NULL
);


-- ════════════════════════════════════════════════════════════
-- [4] 1:1 문의 - 채팅 메시지(CHAT_MESSAGE) 테이블
-- ════════════════════════════════════════════════════════════
CREATE TABLE chat_message (
  message_no      NUMBER GENERATED BY DEFAULT AS IDENTITY,
  room_no         NUMBER NOT NULL,
  sender_no       NUMBER,
  message_content VARCHAR2(2000 CHAR) NOT NULL,
  read_yn         CHAR(1) DEFAULT 'N' NOT NULL,
  created_date    TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,

  CONSTRAINT pk_chat_message PRIMARY KEY (message_no),
  CONSTRAINT ck_chat_message_read CHECK (read_yn IN ('Y', 'N')),
  CONSTRAINT fk_chat_message_room FOREIGN KEY (room_no)
      REFERENCES chat_room (room_no) ON DELETE CASCADE,
  CONSTRAINT fk_chat_message_sender FOREIGN KEY (sender_no)
      REFERENCES member (no) ON DELETE SET NULL
);

-- ════════════════════════════════════════════════════════════
-- [5] 인덱스
-- ════════════════════════════════════════════════════════════
CREATE INDEX idx_chat_room_user_no
    ON chat_room (user_no);

CREATE INDEX idx_chat_room_admin_no
    ON chat_room (admin_no);

CREATE INDEX idx_chat_room_status
    ON chat_room (status);

CREATE INDEX idx_chat_room_category
    ON chat_room (category);

CREATE INDEX idx_chat_room_last_message_date
    ON chat_room (last_message_date);

CREATE INDEX idx_chat_message_room_no
    ON chat_message (room_no);

CREATE INDEX idx_chat_message_created_date
    ON chat_message (created_date);

CREATE TABLE NEWS (
                      NEWS_ID NUMBER PRIMARY KEY,
                      TITLE VARCHAR2(300) NOT NULL,
                      SUMMARY VARCHAR2(1000),
                      SOURCE VARCHAR2(100),
                      PUBLISHED_AT VARCHAR2(50),
                      LINK VARCHAR2(1000),
                      CREATED_AT DATE DEFAULT SYSDATE
);

CREATE SEQUENCE NEWS_SEQ
    START WITH 1
    INCREMENT BY 1
    NOCACHE;

INSERT INTO NEWS (
    NEWS_ID,
    TITLE,
    SUMMARY,
    SOURCE,
    PUBLISHED_AT,
    LINK
) VALUES (
             NEWS_SEQ.NEXTVAL,
             'AI 산업 관련 주요 뉴스',
             'AI 기술이 여러 산업 분야에 빠르게 적용되고 있다는 내용의 뉴스입니다.',
             '테크뉴스',
             '2026-07-07',
             'https://example.com/news/1'
         );

INSERT INTO NEWS (
    NEWS_ID,
    TITLE,
    SUMMARY,
    SOURCE,
    PUBLISHED_AT,
    LINK
) VALUES (
             NEWS_SEQ.NEXTVAL,
             '오늘의 경제 뉴스 요약',
             '환율과 금리 흐름이 시장에 영향을 주고 있다는 경제 뉴스 요약입니다.',
             '경제신문',
             '2026-07-07',
             'https://example.com/news/2'
         );

INSERT INTO NEWS (
    NEWS_ID,
    TITLE,
    SUMMARY,
    SOURCE,
    PUBLISHED_AT,
    LINK
) VALUES (
             NEWS_SEQ.NEXTVAL,
             '개발자 채용 시장 동향',
             '기업들의 개발자 채용 방식과 요구 역량이 변화하고 있다는 기사입니다.',
             'IT데일리',
             '2026-07-07',
             'https://example.com/news/3'
         );

COMMIT;

CREATE TABLE stock_info (
                            stock_id NUMBER PRIMARY KEY,
                            symbol VARCHAR2(20) NOT NULL,
                            stock_name VARCHAR2(100) NOT NULL,
                            price NUMBER DEFAULT 0,
                            change_price NUMBER DEFAULT 0,
                            change_rate NUMBER(10, 2) DEFAULT 0
);

INSERT INTO stock_info VALUES (1, '005930', '삼성전자', 78000, 500, 0.65);
INSERT INTO stock_info VALUES (2, '035420', 'NAVER', 210000, -1500, -0.71);
INSERT INTO stock_info VALUES (3, '035720', '카카오', 56000, 800, 1.45);
INSERT INTO stock_info VALUES (4, '000660', 'SK하이닉스', 235000, 3000, 1.29);

COMMIT;