-- ════════════════════════════════════════════════════════════
-- [1] 회원(MEMBER) 테이블
--     역할: 일반 회원 + 관리자를 한 테이블에서 관리(role로 구분)
--     참조 관계: 이 테이블의 NO(회원번호)를 CHAT_ROOM, CHAT_MESSAGE가 참조(부모 테이블)
-- ════════════════════════════════════════════════════════════
CREATE TABLE member
(
    no               NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,    -- 회원 번호(PK). 값 안 넣으면 1,2,3.. 자동 증가(IDENTITY)
    member_id        VARCHAR2(100) UNIQUE NOT NULL,                          -- 로그인 아이디. UNIQUE=중복 불가, NOT NULL=빈 값 불가(단일 컬럼 인라인)
    password         VARCHAR2(255),                                          -- 비밀번호(해시). 소셜 회원은 없을 수 있어 NULL 허용
    name             VARCHAR2(50) NOT NULL,                                  -- 이름. 필수 값
    nickname         VARCHAR2(50),                                           -- 닉네임. 선택 값
    email            VARCHAR2(100),                                          -- 이메일. 선택 값
    phone            VARCHAR2(20),                                           -- 전화번호. 앞자리 0 보존 위해 문자열
    birth_date       DATE,                                                   -- 생년월일. 날짜형
    gender           VARCHAR2(10),                                           -- 성별. 'M'/'F' 등
    postcode         VARCHAR2(10),                                           -- 우편번호. 계산 안 하므로 문자열
    address          VARCHAR2(255),                                          -- 기본 주소
    detail_address   VARCHAR2(255),                                          -- 상세 주소
    role             VARCHAR2(20) DEFAULT 'USER' NOT NULL,                   -- 권한. 값 안 넣으면 'USER'. 관리자는 'ADMIN'(별도 테이블 대신 이 컬럼으로 구분)
    provider         VARCHAR2(30) DEFAULT 'LOCAL' NOT NULL,-- 가입 방식. 일반='LOCAL', 소셜='KAKAO'/'NAVER'/'GOOGLE' 등
    provider_id      VARCHAR2(255),                                          -- 소셜 로그인 시 업체가 준 고유 ID. 일반 가입이면 NULL
    profile_image    VARCHAR2(500),                                          -- 프로필 이미지 경로(URL). 길 수 있어 500
    last_login_date  TIMESTAMP,                                              -- 마지막 로그인 시각(날짜+시간)
    agree_terms_yn   CHAR(1)   DEFAULT 'N' NOT NULL,                         -- 이용약관 동의. 'Y'/'N'
    agree_privacy_yn CHAR(1)   DEFAULT 'N' NOT NULL,                         -- 개인정보 동의. 'Y'/'N'
    regdate          TIMESTAMP DEFAULT SYSTIMESTAMP,                         -- 가입일시. 값 안 넣으면 현재 시각 자동
    is_deleted       CHAR(1)   DEFAULT 'N',                                  -- 탈퇴 여부. 행 삭제 대신 'Y'로 바꾸는 소프트 삭제용

    -- ──── 제약조건 모음 ────
    CONSTRAINT uk_member_provider UNIQUE (provider, provider_id),            -- (가입방식+소셜ID) 조합 중복 방지(복합이라 아래로 뺌)
    CONSTRAINT ck_member_role CHECK (role IN ('USER', 'ADMIN')),             -- role은 'USER'/'ADMIN'만 허용
    CONSTRAINT ck_member_is_deleted CHECK (is_deleted IN ('Y', 'N')),        -- is_deleted는 'Y'/'N'만 허용
    CONSTRAINT ck_member_agree_terms CHECK (agree_terms_yn IN ('Y', 'N')),   -- 약관 동의는 'Y'/'N'만 허용
    CONSTRAINT ck_member_agree_privacy CHECK (agree_privacy_yn IN ('Y', 'N'))-- 개인정보 동의는 'Y'/'N'만 허용
);


-- ════════════════════════════════════════════════════════════
-- [2] 관리자(ADMIN) 테이블
--     별도로 만들지 않음. member 테이블에 role='ADMIN'으로 통합.
-- ════════════════════════════════════════════════════════════


-- ════════════════════════════════════════════════════════════
-- [3] 1:1 문의 - 채팅방(CHAT_ROOM) 테이블
--     역할: 회원 1명 + 관리자 1명이 대화하는 "문의방" 하나
--     참조(부모): MEMBER(NO) ← USER_NO, ADMIN_NO 둘 다
--     참조(자식): CHAT_MESSAGE가 이 테이블의 ROOM_NO를 참조
-- ════════════════════════════════════════════════════════════
CREATE TABLE chat_room
(
    room_no           NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,      -- 채팅방 번호(PK). IDENTITY 자동 증가
    user_no           NUMBER               NOT NULL,                            -- 문의한 회원 번호. 필수. MEMBER(NO) 참조
    admin_no          NUMBER,                                                   -- 담당 관리자 번호. 미배정이면 NULL. MEMBER(NO) 참조
    status            VARCHAR2(20) DEFAULT 'OPEN' NOT NULL,                     -- 문의 상태. 시작 시 'OPEN', 종료 시 'CLOSED'
    last_message      VARCHAR2(1000),                                           -- 최근 메시지 미리보기(중복 저장). 목록 조회 속도용
    last_message_date DATE,                                                     -- 최근 메시지 시각(중복 저장)
    created_date      DATE DEFAULT SYSDATE NOT NULL,                            -- 방 생성일. 값 안 넣으면 현재 날짜 자동
    closed_date       DATE,                                                     -- 방 종료일. 안 닫혔으면 NULL

    -- ──── 제약조건 모음 ────
    CONSTRAINT ck_chat_room_status CHECK (status IN ('OPEN', 'CLOSED')),        -- status는 'OPEN'/'CLOSED'만 허용
    CONSTRAINT fk_chat_room_user FOREIGN KEY (user_no) REFERENCES member (no),  -- 【참조】문의자는 member에 있는 회원이어야 함
    CONSTRAINT fk_chat_room_admin FOREIGN KEY (admin_no) REFERENCES member (no) -- 【참조】담당 관리자도 member(role='ADMIN')여야 함
);


-- ════════════════════════════════════════════════════════════
-- [4] 1:1 문의 - 채팅 메시지(CHAT_MESSAGE) 테이블
--     역할: 채팅방 안에서 오간 메시지 한 건 한 건
--     참조(부모): CHAT_ROOM(ROOM_NO) ← ROOM_NO,  MEMBER(NO) ← SENDER_NO
-- ════════════════════════════════════════════════════════════
CREATE TABLE chat_message
(
    message_no      NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,                                    -- 메시지 번호(PK). IDENTITY 자동 증가
    room_no         NUMBER                  NOT NULL,                                                       -- 소속 채팅방 번호. 필수. CHAT_ROOM(ROOM_NO) 참조
    sender_no       NUMBER                  NOT NULL,                                                       -- 보낸 사람 회원 번호. 회원/관리자 모두 member라 한 컬럼으로 충분
    message_content VARCHAR2(2000) NOT NULL,                                                                -- 메시지 내용. 빈 메시지 없으므로 필수
    read_yn         CHAR(1) DEFAULT 'N'     NOT NULL,                                                       -- 읽음 여부. 'N'(안 읽음)→'Y'(읽음)
    created_date    DATE    DEFAULT SYSDATE NOT NULL,                                                       -- 메시지 보낸 시각. 값 안 넣으면 현재 날짜 자동

    -- ──── 제약조건 모음 ────
    CONSTRAINT ck_chat_message_read CHECK (read_yn IN ('Y', 'N')),                                          -- read_yn은 'Y'/'N'만 허용
    CONSTRAINT fk_chat_message_room FOREIGN KEY (room_no) REFERENCES chat_room (room_no) ON DELETE CASCADE, -- 【참조】방 삭제 시 메시지도 자동 삭제
    CONSTRAINT fk_chat_message_sender FOREIGN KEY (sender_no) REFERENCES member (no)                        -- 【참조】보낸 사람은 member에 있는 회원이어야 함
);


-- ════════════════════════════════════════════════════════════
-- [5] 인덱스 = "책 뒤 찾아보기(색인)". 자주 검색하는 컬럼을 빨리 찾기 위함
--     PK 컬럼은 색인 자동 생성 → 아래는 PK가 아닌 컬럼에 추가로 생성
-- ════════════════════════════════════════════════════════════
CREATE INDEX idx_chat_room_user_no ON chat_room (user_no); -- 특정 회원의 문의방 목록 조회 (WHERE user_no = ?)
CREATE INDEX idx_chat_room_admin_no ON chat_room (admin_no); -- 특정 관리자 담당 문의방 목록 조회 (WHERE admin_no = ?)
CREATE INDEX idx_chat_message_room_no ON chat_message (room_no); -- 특정 방의 메시지 전체 조회 (WHERE room_no = ?)
CREATE INDEX idx_chat_message_created_date ON chat_message (created_date);-- 메시지 시간순 정렬 (ORDER BY created_date)