spring:
  application:
    name: it-project-2nd
  devtools:
    livereload:
      enabled: true
    restart:
      enabled: true
  thymeleaf:
    cache: false
  datasource:
    driver-class-name: oracle.jdbc.OracleDriver
    url: jdbc:oracle:thin:@localhost:1521:xe
    username: secondpro
    password: 1234
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 1000MB
  data:
    redis:
      host: localhost
      port: 6379

mybatis:
  mapper-locations:  classpath:/mapper/**/*.xml
  type-aliases-package: com.siyan1234.itproject2nd
  configuration:
    map-underscore-to-camel-case: true
