-- ════════════════════════════════════════════════════════════
-- secondpro 프로젝트 최신 전체 테이블 생성 SQL
-- ════════════════════════════════════════════════════════════
-- 1. 테이블이 없는 빈 DB 또는 00_reset_local.sql 실행 후 사용
-- 2. 기존 테이블이 남아 있으면 이미 존재하는 객체 오류 발생
-- 3. 이 파일에는 현재 최신 구조가 모두 반영
-- 4. 이 파일을 실행하면 V001~V004 마이그레이션 파일은 실행하지 않음
-- 5. 실행 후 샘플 데이터가 필요하면 02_seed_data.sql을 실행
-- ════════════════════════════════════════════════════════════
-- 실행 순서: member → social_account → chat_room → chat_message
--            → news → stock_info → visit_log
--            → board → board_file → board_comment
--            → calendar_event → google_calendar_token → 인덱스
-- ════════════════════════════════════════════════════════════


-- ════════════════════════════════════════════════════════════
-- [1] 회원(MEMBER) 테이블
-- ════════════════════════════════════════════════════════════
CREATE TABLE member (
    no                NUMBER GENERATED BY DEFAULT AS IDENTITY,
    member_id         VARCHAR2(100 CHAR),
    password          VARCHAR2(255 CHAR),
    name              VARCHAR2(50 CHAR),
    nickname          VARCHAR2(50 CHAR) NOT NULL,
    email             VARCHAR2(100 CHAR),
    phone             VARCHAR2(20 CHAR),
    birth_date        DATE,
    gender            VARCHAR2(10 CHAR),
    postcode          VARCHAR2(10 CHAR),
    address           VARCHAR2(255 CHAR),
    detail_address    VARCHAR2(255 CHAR),
    role              VARCHAR2(20 CHAR) DEFAULT 'USER' NOT NULL,
    profile_image     VARCHAR2(500 CHAR),
    last_login_date   TIMESTAMP,
    agree_terms_yn    CHAR(1) DEFAULT 'N' NOT NULL,
    agree_privacy_yn  CHAR(1) DEFAULT 'N' NOT NULL,
    regdate           TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    ban_yn            CHAR(1) DEFAULT 'N' NOT NULL,
    ban_reason        VARCHAR2(500 CHAR),
    banned_date       TIMESTAMP,
    banned_by         NUMBER,

    CONSTRAINT pk_member PRIMARY KEY (no),
    CONSTRAINT uk_member_member_id UNIQUE (member_id),
    CONSTRAINT uk_member_email UNIQUE (email),
    CONSTRAINT uk_member_nickname UNIQUE (nickname),
    CONSTRAINT ck_member_role CHECK (role IN ('USER', 'ADMIN')),
    CONSTRAINT ck_member_agree_terms CHECK (agree_terms_yn IN ('Y', 'N')),
    CONSTRAINT ck_member_agree_privacy CHECK (agree_privacy_yn IN ('Y', 'N')),
    CONSTRAINT ck_member_ban CHECK (ban_yn IN ('Y', 'N')),
    CONSTRAINT fk_member_banned_by FOREIGN KEY (banned_by)
        REFERENCES member(no) ON DELETE SET NULL
);

COMMENT ON COLUMN member.ban_yn IS '관리자 정지 여부(Y/N)';
COMMENT ON COLUMN member.ban_reason IS '관리자 정지 사유';
COMMENT ON COLUMN member.banned_date IS '관리자 정지 처리 시각';
COMMENT ON COLUMN member.banned_by IS '정지 처리 관리자 회원번호';


-- ════════════════════════════════════════════════════════════
-- [2] 소셜 계정(SOCIAL_ACCOUNT) 테이블
-- ════════════════════════════════════════════════════════════
CREATE TABLE social_account (
    no            NUMBER GENERATED BY DEFAULT AS IDENTITY,
    member_no     NUMBER NOT NULL,
    provider      VARCHAR2(30 CHAR) NOT NULL,
    provider_id   VARCHAR2(255 CHAR) NOT NULL,
    created_date  TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,

    CONSTRAINT pk_social_account PRIMARY KEY (no),
    CONSTRAINT uk_social_provider UNIQUE (provider, provider_id),
    CONSTRAINT fk_social_member FOREIGN KEY (member_no)
        REFERENCES member(no) ON DELETE CASCADE
);


-- ════════════════════════════════════════════════════════════
-- [3] 1:1 문의 - 채팅방(CHAT_ROOM) 테이블
-- ════════════════════════════════════════════════════════════
CREATE TABLE chat_room (
    room_no            NUMBER GENERATED BY DEFAULT AS IDENTITY,
    user_no            NUMBER,
    admin_no           NUMBER,
    status             VARCHAR2(20 CHAR) DEFAULT 'OPEN' NOT NULL,
    category           VARCHAR2(30 CHAR) DEFAULT 'ETC' NOT NULL,
    last_message       VARCHAR2(1000 CHAR),
    last_message_date  TIMESTAMP,
    created_date       TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    closed_date        TIMESTAMP,

    CONSTRAINT pk_chat_room PRIMARY KEY (room_no),
    CONSTRAINT ck_chat_room_status CHECK (status IN ('OPEN', 'CLOSED')),
    CONSTRAINT ck_chat_room_category CHECK (
        category IN (
            'MAIL',
            'MAP',
            'STOCK',
            'NEWS',
            'WEATHER',
            'CALENDAR',
            'ETC'
        )
    ),
    CONSTRAINT fk_chat_room_user FOREIGN KEY (user_no)
        REFERENCES member(no) ON DELETE SET NULL,
    CONSTRAINT fk_chat_room_admin FOREIGN KEY (admin_no)
        REFERENCES member(no) ON DELETE SET NULL
);


-- ════════════════════════════════════════════════════════════
-- [4] 1:1 문의 - 채팅 메시지(CHAT_MESSAGE) 테이블
-- ════════════════════════════════════════════════════════════
CREATE TABLE chat_message (
    message_no       NUMBER GENERATED BY DEFAULT AS IDENTITY,
    room_no          NUMBER NOT NULL,
    sender_no        NUMBER,
    message_content  VARCHAR2(2000 CHAR) NOT NULL,
    read_yn          CHAR(1) DEFAULT 'N' NOT NULL,
    created_date     TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,

    CONSTRAINT pk_chat_message PRIMARY KEY (message_no),
    CONSTRAINT ck_chat_message_read CHECK (read_yn IN ('Y', 'N')),
    CONSTRAINT fk_chat_message_room FOREIGN KEY (room_no)
        REFERENCES chat_room(room_no) ON DELETE CASCADE,
    CONSTRAINT fk_chat_message_sender FOREIGN KEY (sender_no)
        REFERENCES member(no) ON DELETE SET NULL
);


-- ════════════════════════════════════════════════════════════
-- [5] 뉴스(NEWS) 테이블
-- ════════════════════════════════════════════════════════════
CREATE TABLE news (
    news_id       NUMBER,
    title         VARCHAR2(300) NOT NULL,
    summary       VARCHAR2(1000),
    source        VARCHAR2(100),
    published_at  VARCHAR2(50),
    link          VARCHAR2(1000),
    created_at    DATE DEFAULT SYSDATE,

    CONSTRAINT pk_news PRIMARY KEY (news_id)
);

CREATE SEQUENCE news_seq
    START WITH 1
    INCREMENT BY 1
    NOCACHE;


-- ════════════════════════════════════════════════════════════
-- [6] 주식 정보(STOCK_INFO) 테이블
-- ════════════════════════════════════════════════════════════
CREATE TABLE stock_info (
    stock_id      NUMBER,
    symbol        VARCHAR2(20) NOT NULL,
    stock_name    VARCHAR2(100) NOT NULL,
    price         NUMBER DEFAULT 0,
    change_price  NUMBER DEFAULT 0,
    change_rate   NUMBER(10, 2) DEFAULT 0,

    CONSTRAINT pk_stock_info PRIMARY KEY (stock_id)
);


-- ════════════════════════════════════════════════════════════
-- [7] 방문 로그(VISIT_LOG) 테이블
-- 사용자가 분석 쿠키를 허용한 경우에만 저장
-- ════════════════════════════════════════════════════════════
CREATE TABLE visit_log (
    no              NUMBER GENERATED BY DEFAULT AS IDENTITY,
    member_no       NUMBER,
    session_id      VARCHAR2(100 CHAR),
    request_uri     VARCHAR2(500 CHAR),
    query_string    VARCHAR2(1000 CHAR),
    request_method  VARCHAR2(20 CHAR),
    user_agent      VARCHAR2(1000 CHAR),
    ip_address      VARCHAR2(100 CHAR),
    referer         VARCHAR2(1000 CHAR),
    created_date    TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,

    CONSTRAINT pk_visit_log PRIMARY KEY (no),
    CONSTRAINT fk_visit_log_member FOREIGN KEY (member_no)
        REFERENCES member(no) ON DELETE SET NULL
);


-- ════════════════════════════════════════════════════════════
-- [8] 게시판(BOARD) 테이블
-- ════════════════════════════════════════════════════════════
CREATE TABLE board (
    no             NUMBER GENERATED BY DEFAULT AS IDENTITY,
    writer_no      NUMBER,
    category       VARCHAR2(20 CHAR) DEFAULT 'NOTICE' NOT NULL,
    title          VARCHAR2(200 CHAR) NOT NULL,
    content        CLOB NOT NULL,
    view_count     NUMBER DEFAULT 0 NOT NULL,
    created_date   TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    modified_date  TIMESTAMP,

    CONSTRAINT pk_board PRIMARY KEY (no),
    CONSTRAINT ck_board_category CHECK (category IN ('NOTICE', 'FAQ', 'FREE')),
    CONSTRAINT fk_board_writer FOREIGN KEY (writer_no)
        REFERENCES member(no) ON DELETE SET NULL
);


-- ════════════════════════════════════════════════════════════
-- [9] 게시판 첨부파일(BOARD_FILE) 테이블
-- ════════════════════════════════════════════════════════════
CREATE TABLE board_file (
    no             NUMBER GENERATED BY DEFAULT AS IDENTITY,
    board_no       NUMBER NOT NULL,
    origin_name    VARCHAR2(255 CHAR) NOT NULL,
    stored_name    VARCHAR2(255 CHAR) NOT NULL,
    file_path      VARCHAR2(500 CHAR) NOT NULL,
    file_size      NUMBER NOT NULL,
    created_date   TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,

    CONSTRAINT pk_board_file PRIMARY KEY (no),
    CONSTRAINT fk_board_file_board FOREIGN KEY (board_no)
        REFERENCES board(no) ON DELETE CASCADE
);


-- ════════════════════════════════════════════════════════════
-- [10] 게시판 댓글(BOARD_COMMENT) 테이블
-- ════════════════════════════════════════════════════════════
CREATE TABLE board_comment (
    no             NUMBER GENERATED BY DEFAULT AS IDENTITY,
    board_no       NUMBER NOT NULL,
    writer_no      NUMBER,
    content        VARCHAR2(1000 CHAR) NOT NULL,
    created_date   TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    modified_date  TIMESTAMP,

    CONSTRAINT pk_board_comment PRIMARY KEY (no),
    CONSTRAINT fk_board_comment_board FOREIGN KEY (board_no)
        REFERENCES board(no) ON DELETE CASCADE,
    CONSTRAINT fk_board_comment_writer FOREIGN KEY (writer_no)
        REFERENCES member(no) ON DELETE SET NULL
);


-- ════════════════════════════════════════════════════════════
-- [11] 캘린더 일정(CALENDAR_EVENT) 테이블
-- 우리 사이트 일정과 구글 캘린더 일정을 저장
-- ════════════════════════════════════════════════════════════
CREATE TABLE calendar_event (
    no                       NUMBER GENERATED BY DEFAULT AS IDENTITY,
    member_no                NUMBER NOT NULL,
    title                    VARCHAR2(200 CHAR) NOT NULL,
    content                  VARCHAR2(1000 CHAR),
    location                 VARCHAR2(300 CHAR),
    start_datetime           TIMESTAMP NOT NULL,
    end_datetime             TIMESTAMP,
    all_day_yn               CHAR(1) DEFAULT 'Y' NOT NULL,
    source_type              VARCHAR2(20 CHAR) DEFAULT 'LOCAL' NOT NULL,
    google_event_id          VARCHAR2(255 CHAR),
    google_calendar_id       VARCHAR2(255 CHAR) DEFAULT 'primary',
    google_updated_datetime  TIMESTAMP,
    is_deleted               CHAR(1) DEFAULT 'N' NOT NULL,
    regdate                  TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    updatedate               TIMESTAMP,

    CONSTRAINT pk_calendar_event PRIMARY KEY (no),
    CONSTRAINT ck_calendar_event_all_day CHECK (all_day_yn IN ('Y', 'N')),
    CONSTRAINT ck_calendar_event_source CHECK (source_type IN ('LOCAL', 'GOOGLE')),
    CONSTRAINT ck_calendar_event_deleted CHECK (is_deleted IN ('Y', 'N')),
    CONSTRAINT fk_calendar_event_member FOREIGN KEY (member_no)
        REFERENCES member(no) ON DELETE CASCADE
);


-- ════════════════════════════════════════════════════════════
-- [12] 구글 캘린더 연동 토큰(GOOGLE_CALENDAR_TOKEN) 테이블
-- 회원이 구글 캘린더 연동을 허용했을 때 토큰 저장
-- 기존 로그인 방식은 건드리지 않고 member.no 값으로 회원과 연결
-- ════════════════════════════════════════════════════════════
CREATE TABLE google_calendar_token (
    no             NUMBER GENERATED BY DEFAULT AS IDENTITY,
    member_no      NUMBER NOT NULL,
    access_token   CLOB,
    refresh_token  CLOB,
    token_expiry   TIMESTAMP,
    google_email   VARCHAR2(255 CHAR),
    regdate        TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,

    CONSTRAINT pk_google_calendar_token PRIMARY KEY (no),
    CONSTRAINT uk_google_calendar_token_member UNIQUE (member_no),
    CONSTRAINT fk_google_calendar_token_member FOREIGN KEY (member_no)
        REFERENCES member(no) ON DELETE CASCADE
);


-- ════════════════════════════════════════════════════════════
-- [13] 인덱스 - 회원·소셜·채팅·방문 기록
-- ════════════════════════════════════════════════════════════
CREATE INDEX idx_social_member_no
    ON social_account(member_no);

CREATE INDEX idx_chat_room_user_no
    ON chat_room(user_no);

CREATE INDEX idx_chat_room_admin_no
    ON chat_room(admin_no);

CREATE INDEX idx_chat_room_status
    ON chat_room(status);

CREATE INDEX idx_chat_room_category
    ON chat_room(category);

CREATE INDEX idx_chat_room_last_message_date
    ON chat_room(last_message_date);

CREATE INDEX idx_chat_message_room_no
    ON chat_message(room_no);

CREATE INDEX idx_chat_message_created_date
    ON chat_message(created_date);

CREATE INDEX idx_visit_log_member_no
    ON visit_log(member_no);

CREATE INDEX idx_visit_log_created_date
    ON visit_log(created_date);

CREATE INDEX idx_visit_log_request_uri
    ON visit_log(request_uri);


-- ════════════════════════════════════════════════════════════
-- [14] 인덱스 - 게시판
-- ════════════════════════════════════════════════════════════
CREATE INDEX idx_board_writer_no
    ON board(writer_no);

CREATE INDEX idx_board_created_date
    ON board(created_date);

CREATE INDEX idx_board_category
    ON board(category);

CREATE INDEX idx_board_file_board_no
    ON board_file(board_no);

CREATE INDEX idx_board_comment_board_no
    ON board_comment(board_no);

CREATE INDEX idx_board_comment_writer_no
    ON board_comment(writer_no);


-- ════════════════════════════════════════════════════════════
-- [15] 인덱스 - 캘린더
-- 회원별 월간 일정 조회 속도 개선
-- ════════════════════════════════════════════════════════════
CREATE INDEX idx_calendar_event_member_date
    ON calendar_event(member_no, start_datetime);
