-- ════════════════════════════════════════════════════════════
-- secondpro 수동 마이그레이션 V002
-- 변경 내용: NEWS·STOCK_INFO·VISIT_LOG 테이블 추가
-- ════════════════════════════════════════════════════════════
-- 1. MEMBER 테이블이 먼저 존재해야 VISIT_LOG 외래 키를 만들 수 있음
-- 2. 샘플 데이터는 이 파일이 아니라 02_seed_data.sql에서 관리
-- ════════════════════════════════════════════════════════════


-- ════════════════════════════════════════════════════════════
-- [1] 뉴스(NEWS) 테이블과 시퀀스
-- ════════════════════════════════════════════════════════════
CREATE TABLE news (
    news_id       NUMBER,
    title         VARCHAR2(300) NOT NULL,
    summary       VARCHAR2(1000),
    source        VARCHAR2(100),
    published_at  VARCHAR2(50),
    link          VARCHAR2(1000),
    created_at    DATE DEFAULT SYSDATE,

    CONSTRAINT pk_news PRIMARY KEY (news_id)
);

CREATE SEQUENCE news_seq
    START WITH 1
    INCREMENT BY 1
    NOCACHE;


-- ════════════════════════════════════════════════════════════
-- [2] 주식 정보(STOCK_INFO) 테이블
-- ════════════════════════════════════════════════════════════
CREATE TABLE stock_info (
    stock_id      NUMBER,
    symbol        VARCHAR2(20) NOT NULL,
    stock_name    VARCHAR2(100) NOT NULL,
    price         NUMBER DEFAULT 0,
    change_price  NUMBER DEFAULT 0,
    change_rate   NUMBER(10, 2) DEFAULT 0,

    CONSTRAINT pk_stock_info PRIMARY KEY (stock_id)
);


-- ════════════════════════════════════════════════════════════
-- [3] 방문 로그(VISIT_LOG) 테이블
-- ════════════════════════════════════════════════════════════
CREATE TABLE visit_log (
    no              NUMBER GENERATED BY DEFAULT AS IDENTITY,
    member_no       NUMBER,
    session_id      VARCHAR2(100 CHAR),
    request_uri     VARCHAR2(500 CHAR),
    query_string    VARCHAR2(1000 CHAR),
    request_method  VARCHAR2(20 CHAR),
    user_agent      VARCHAR2(1000 CHAR),
    ip_address      VARCHAR2(100 CHAR),
    referer         VARCHAR2(1000 CHAR),
    created_date    TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,

    CONSTRAINT pk_visit_log PRIMARY KEY (no),
    CONSTRAINT fk_visit_log_member FOREIGN KEY (member_no)
        REFERENCES member(no) ON DELETE SET NULL
);

CREATE INDEX idx_visit_log_member_no
    ON visit_log(member_no);

CREATE INDEX idx_visit_log_created_date
    ON visit_log(created_date);

CREATE INDEX idx_visit_log_request_uri
    ON visit_log(request_uri);
