-- 1. 이 파일은 이력 보관용. 평소에는 실행하지 않음 (01_schema_latest.sql에 이미 포함)
-- 2. 기존 데이터를 유지한 채 캘린더 테이블만 추가해야 하는 경우에만 실행
-- 3. 한 번만 실행. 두 번 실행하면 이미 존재하는 객체 오류 발생
-- 4. MEMBER 테이블이 먼저 존재해야 외래 키 생성 가능


-- ════════════════════════════════════════════════════════════
-- [1] 캘린더 일정(CALENDAR_EVENT) 테이블
-- 우리 사이트 일정과 구글 캘린더 일정을 저장
-- ════════════════════════════════════════════════════════════
CREATE TABLE calendar_event (
    no                       NUMBER GENERATED BY DEFAULT AS IDENTITY,
    member_no                NUMBER NOT NULL,
    title                    VARCHAR2(200 CHAR) NOT NULL,
    content                  VARCHAR2(1000 CHAR),
    location                 VARCHAR2(300 CHAR),
    start_datetime           TIMESTAMP NOT NULL,
    end_datetime             TIMESTAMP,
    all_day_yn               CHAR(1) DEFAULT 'Y' NOT NULL,
    source_type              VARCHAR2(20 CHAR) DEFAULT 'LOCAL' NOT NULL,
    google_event_id          VARCHAR2(255 CHAR),
    google_calendar_id       VARCHAR2(255 CHAR) DEFAULT 'primary',
    google_updated_datetime  TIMESTAMP,
    is_deleted               CHAR(1) DEFAULT 'N' NOT NULL,
    regdate                  TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    updatedate               TIMESTAMP,

    CONSTRAINT pk_calendar_event PRIMARY KEY (no),
    CONSTRAINT ck_calendar_event_all_day CHECK (all_day_yn IN ('Y', 'N')),
    CONSTRAINT ck_calendar_event_source CHECK (source_type IN ('LOCAL', 'GOOGLE')),
    CONSTRAINT ck_calendar_event_deleted CHECK (is_deleted IN ('Y', 'N')),
    CONSTRAINT fk_calendar_event_member FOREIGN KEY (member_no)
        REFERENCES member(no) ON DELETE CASCADE
);


-- ════════════════════════════════════════════════════════════
-- [2] 구글 캘린더 연동 토큰(GOOGLE_CALENDAR_TOKEN) 테이블
-- 회원이 구글 캘린더 연동을 허용했을 때 토큰 저장
-- 기존 로그인 방식은 건드리지 않고 member.no 값으로 회원과 연결
-- ════════════════════════════════════════════════════════════
CREATE TABLE google_calendar_token (
    no             NUMBER GENERATED BY DEFAULT AS IDENTITY,
    member_no      NUMBER NOT NULL,
    access_token   CLOB,
    refresh_token  CLOB,
    token_expiry   TIMESTAMP,
    google_email   VARCHAR2(255 CHAR),
    regdate        TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,

    CONSTRAINT pk_google_calendar_token PRIMARY KEY (no),
    CONSTRAINT uk_google_calendar_token_member UNIQUE (member_no),
    CONSTRAINT fk_google_calendar_token_member FOREIGN KEY (member_no)
        REFERENCES member(no) ON DELETE CASCADE
);


-- ════════════════════════════════════════════════════════════
-- [3] 인덱스 - 캘린더
-- 회원별 월간 일정 조회 속도 개선
-- ════════════════════════════════════════════════════════════
CREATE INDEX idx_calendar_event_member_date
    ON calendar_event(member_no, start_datetime);
