-- 1. 이 파일은 이력 보관용. 평소에는 실행하지 않음 (01_schema_latest.sql에 이미 포함)
-- 2. 기존 데이터를 유지한 채 비회원 문의 기능만 추가해야 하는 경우에만 실행
-- 3. 한 번만 실행. 두 번 실행하면 이미 존재하는 객체 오류 발생
-- 4. BOARD 테이블이 먼저 존재해야 함
-- 5. 기존 게시글의 guest_author_no는 NULL로 남음(회원이 쓴 글이므로 정상)


-- ════════════════════════════════════════════════════════════
-- [1] 비회원 문의 작성자(GUEST_AUTHOR) 테이블 생성
-- 비회원 문의글 한 건당 작성자 정보 한 건 생성
-- ════════════════════════════════════════════════════════════
CREATE TABLE guest_author (
    no             NUMBER GENERATED BY DEFAULT AS IDENTITY,
    guest_name     VARCHAR2(50 CHAR) NOT NULL,
    password_hash  VARCHAR2(255 CHAR) NOT NULL,
    created_date   TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,

    CONSTRAINT pk_guest_author PRIMARY KEY (no)
);


-- ════════════════════════════════════════════════════════════
-- [2] BOARD에 비회원 작성자 번호 컬럼 추가
-- 기존 게시글은 회원 글이므로 NULL로 남음
-- ════════════════════════════════════════════════════════════
ALTER TABLE board
ADD guest_author_no NUMBER;


-- ════════════════════════════════════════════════════════════
-- [3] 외래 키 추가
-- ON DELETE 옵션 없음 -> 작성자 행이 남아 있으면 board가 참조 유지
-- 비회원 글 삭제는 Service에서 board -> guest_author 순으로 직접 삭제
-- ════════════════════════════════════════════════════════════
ALTER TABLE board
ADD CONSTRAINT fk_board_guest_author
FOREIGN KEY (guest_author_no)
REFERENCES guest_author(no);


-- ════════════════════════════════════════════════════════════
-- [4] 1:1 제약조건 추가
-- 비회원 작성자 한 행은 게시글 하나에만 연결
-- Oracle 단일 컬럼 UNIQUE는 NULL 중복을 허용하므로
-- 회원이 쓴 글(guest_author_no = NULL)이 아무리 많아도 충돌하지 않음
--
-- 이 UNIQUE 제약조건을 만들면 Oracle이 guest_author_no 컬럼에
-- 고유 인덱스를 자동으로 생성, 따라서 같은 컬럼에
-- CREATE INDEX를 별도로 만들면 ORA-01408 오류가 발생.
-- 별도 인덱스는 만들지 않는다.
-- ════════════════════════════════════════════════════════════
ALTER TABLE board
ADD CONSTRAINT uk_board_guest_author
UNIQUE (guest_author_no);
