-- ════════════════════════════════════════════════════════════
-- secondpro 수동 마이그레이션 V007
-- 변경 내용: 지도 장소 즐겨찾기 테이블 추가
-- ════════════════════════════════════════════════════════════
-- 기존 DB를 유지하면서 즐겨찾기 기능만 추가할 때 이 파일을 실행
-- MEMBER 테이블이 먼저 존재해야 함
-- ════════════════════════════════════════════════════════════

CREATE TABLE map_favorite_place (
    favorite_no   NUMBER GENERATED BY DEFAULT AS IDENTITY,
    member_no     NUMBER NOT NULL,
    place_key     VARCHAR2(160 CHAR) NOT NULL,
    place_id      VARCHAR2(100 CHAR),
    place_name    VARCHAR2(200 CHAR) NOT NULL,
    address_name  VARCHAR2(500 CHAR) NOT NULL,
    category_name VARCHAR2(200 CHAR),
    phone         VARCHAR2(50 CHAR),
    place_url     VARCHAR2(1000 CHAR),
    longitude     NUMBER(20, 8) NOT NULL,
    latitude      NUMBER(20, 8) NOT NULL,
    source_type   VARCHAR2(20 CHAR) NOT NULL,
    created_date  TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,

    CONSTRAINT pk_map_favorite_place PRIMARY KEY (favorite_no),
    CONSTRAINT uk_map_favorite_member_place UNIQUE (member_no, place_key),
    CONSTRAINT ck_map_favorite_source CHECK (source_type IN ('PLACE', 'ADDRESS')),
    CONSTRAINT ck_map_favorite_longitude CHECK (longitude BETWEEN 123 AND 132.5),
    CONSTRAINT ck_map_favorite_latitude CHECK (latitude BETWEEN 32 AND 39.8),
    CONSTRAINT fk_map_favorite_member FOREIGN KEY (member_no)
        REFERENCES member(no) ON DELETE CASCADE
);

CREATE INDEX idx_map_favorite_member_date
    ON map_favorite_place(member_no, created_date);
