/* =========================================================
   V011 1:1 채팅 메시지 최대 1,000자 제한

   적용 대상
   - 기존 DB를 계속 사용하는 팀원
   ========================================================= */

-- chat_message 퍼지 작업후  CHAT_MESSAGE 테이블 생성
DROP TABLE chat_message CASCADE CONSTRAINTS PURGE;
-- ════════════════════════════════════════════════════════════
-- [4] 1:1 문의 - 채팅 메시지(CHAT_MESSAGE) 테이블
-- ════════════════════════════════════════════════════════════
CREATE TABLE chat_message (
      message_no       NUMBER GENERATED BY DEFAULT AS IDENTITY,
      room_no          NUMBER NOT NULL,
      sender_no        NUMBER,
      message_content  VARCHAR2(1000 CHAR) NOT NULL,
      read_yn          CHAR(1) DEFAULT 'N' NOT NULL,
      created_date     TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,

      CONSTRAINT pk_chat_message PRIMARY KEY (message_no),
      CONSTRAINT ck_chat_message_read CHECK (read_yn IN ('Y', 'N')),
      CONSTRAINT ck_chat_message_length CHECK (
          TRIM(message_content) IS NOT NULL
              AND LENGTH(message_content) <= 1000
          ),
      CONSTRAINT fk_chat_message_room FOREIGN KEY (room_no)
          REFERENCES chat_room(room_no) ON DELETE CASCADE,
      CONSTRAINT fk_chat_message_sender FOREIGN KEY (sender_no)
          REFERENCES member(no) ON DELETE SET NULL
);
COMMIT;


